[project]
name = "products"
version = "0.1.0"
description = ""
authors = [
    { name = "Sergei Mikurov", email = "454004@mail.ru" }
]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "aiohttp (>=3.14.4,<4.0.0)"
]

[tool.poetry]
packages = [
    { include = "products", from = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
